name: CI

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.env.experimental == true }}
    strategy:
      fail-fast: false
      matrix:
        env:
          - { php: 7.4, symfony: 5.4 }
          - { php: 8.0, symfony: 5.4 }
          - { php: 8.1, symfony: 5.4 }
          - { php: 8.2, symfony: 5.4 }
          - { php: 8.1, symfony: 6.4 }
          - { php: 8.2, symfony: 6.4 }

    steps:
      - uses: actions/checkout@v3

      - name: start tolgee
        run: |
          docker run --restart always --name=tolgee \
            -d -v tolgee_data:/data/ \
            -v "$(pwd)/.gitpod/tolgee/importData/:/importData/" \
            -p 8085:8080 \
            --env-file ./.gitpod/tolgee/.env \
            tolgee/tolgee

      - name: Composer cache
        uses: actions/cache@v3
        with:
          path: "vendor"
          key: ${{ runner.os }}-${{ matrix.env.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.env.php }}

      - name: Configure Symfony
        run: composer config extra.symfony.require "${{ matrix.symfony }}"

      - name: Install composer
        run: composer update --no-progress --ansi --prefer-stable

      - name: Validate composer.json and composer.lock
        run: composer update --no-progress --ansi --prefer-stable --prefer-lowest

      - name: PHPUnit tests
        run: composer run test-cobertura

      - name: "Code Coverage Report"
        if: "${{ matrix.env.php }} == '8.2' && github.event_name == 'pull_request'"
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Add Coverage PR Comment
        if: "${{ matrix.env.php }} == '8.2' && github.event_name == 'pull_request'"
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: code-coverage-results.md
